# Generated by Django 5.0.7 on 2024-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
